name: Build and Upload EXE

on:
  workflow_dispatch: # 添加手动触发

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile 1.py
        ls dist  # 列出 dist 目录的内容

    - name: Compress EXE
      run: |
        zip -j dist/1.zip dist/1.exe  # 将 1.exe 压缩成 1.zip

    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with:
        name: exe-zip
        path: dist/1.zip  # 上传压缩文件
